services:
  database:
    build: ./database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

  train-deploy:
    build: ./train-deploy
    volumes:
      - ./train-deploy:/app
      - ./models:/app/models
    depends_on:
      - experiment-tracking

  experiment-tracking:
    build: ./experiment-tracking
    ports:
      - 5000:5000
    env_file:
      - ./database/.env
    depends_on:
      - database

volumes:
  postgres-data:
