services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./notebooks:/app/notebooks
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
  # prefect:
  #   image: prefecthq/prefect:2-latest
  #   environment:
  #     - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
  #   ports:
  #     - "4200:4200"
  # monitoring:
  #   build: ./monitoring
  #   ports:
  #     - "8050:8050"
  #   environment:
  #     - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
