services:
  database:
    build: ./database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

  train-deploy:
    build: ./train-deploy
    volumes:
      - ./train-deploy:/app
      - mlops-data:/shared/data
      - mlops-models:/shared/models
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - experiment-tracking

  experiment-tracking:
    build: ./experiment-tracking
    ports:
      - 5000:5000
    env_file:
      - ./database/.env
    depends_on:
      - database

  orchestration:
    build:
      context: .
      dockerfile: orchestration/Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./orchestration:/app
      - ./train-deploy:/train-deploy
      - mlops-data:/shared/data
      - mlops-models:/shared/models
    depends_on:
      - experiment-tracking

volumes:
  postgres-data:
  mlops-data:
  mlops-models:
